### ISSUE TITLE
How to validate syntax error in EDIFACT document

### ISSUE THREAD

**Issue by sungung** [smooks/smooks-edi-cartridge#126]
I am trying to figure out how to create document syntax exception when processing EDIFACT data.

I noticed you can get assert exception when it is defined in dfdl.xsd file. At the moment, I only get BadMessage segment when document has faulty but cannot interpret what went wrong.

```
		<D95B:BadMessage>
			<Segment>
				<Name>BGM</Name>
				<Data>2B3338302B494E563030303030312B39</Data>
			</Segment>
			<Segment>
				<Name>DTM</Name>
				<Data>2B333A32303230313133303A313032</Data>
			</Segment>
			<Segment>
				<Name>RFF</Name>
				<Data>2B4F4E3A54455354</Data>
			</Segment>
```

**Comment by claudemamo** [comment]
Presently, `edifact:parser` produces a _BadMessage_ whenever a segment doesn't match the expected structure. _BadMessage_ consists of the document's segments where a _data_  element contains a segment's content represented in hexadecimal. 

As it is, there isn't an easy to know what went wrong. You could turn on debugging by setting `"debugging="true"` in `edifact:parser` but Daffodil's output is very verbose. If you don't mind customising the schema, you could remove the [_BadMessage_ branch](https://github.com/smooks/smooks-edi-cartridge/blob/v2.0.0-M3/common-schemas/src/main/resources/EDIFACT-Common/EDIFACT-Interchange.dfdl.xsd.mustache#L99-L102) from the DFDL schema and let the parsing error bubble up to the application.

**Comment by sungung** [comment]
Claude, removed BadMessage element from the schema then I was able to capture exceptions. It gave better understanding than Daffodil's output.
