### ISSUE TITLE
Add schema support and bindings for post-2019 directories

### ISSUE THREAD

**Issue by uliSchuster** [smooks/smooks-edi-cartridge#172]
Thanks for the fabulous work of the smooks team, I can now parse a whole range of EDIFACT files. For my appllication at hand, some files require the latest directories (D.20a and D.20b, to be precise). Is there a chance that they will be added to the smooks edifact cartridge and bindings? Alternatively, how would I go about creating them from the official directories myself?

**Comment by claudemamo** [comment]
>Is there a chance that they will be added to the smooks edifact cartridge and bindings?

We'll consider the directories for RC2 but don't hold your breath that they'll be added any time soon unless you'd like to sponsor the work.

>Alternatively, how would I go about creating them from the official directories myself?

Should be relatively easy if the free form text is structured like the past directories:

Step 1: [fork](https://github.com/smooks/smooks-edi-cartridge) the repo.
Step 2: copy the new directory archives to the [project fork](https://github.com/smooks/smooks-edi-cartridge/tree/167557abba5ae9079f90df8b0fed00f204ef139d/edifact-schemas/src/main/resources).
Step 3: [add](https://github.com/smooks/smooks-edi-cartridge/blob/167557abba5ae9079f90df8b0fed00f204ef139d/edifact-schemas/pom.xml#L96) the copied archives to the list of directories fed to `EdifactDfdlSchemaGenerator` at build time. 
Step 4: [package](https://github.com/smooks/smooks-edi-cartridge/blob/167557abba5ae9079f90df8b0fed00f204ef139d/edifact-schemas/pom.xml#L873-L886) the generated classes.
Step 5: [follow the pattern](https://github.com/smooks/smooks-edi-cartridge/tree/167557abba5ae9079f90df8b0fed00f204ef139d/edifact-jaxb-bindings) in the `edifact-jaxb-bindings` module to create Maven modules for the new EDIFACT directories.

You might need to [write your own](https://github.com/smooks/smooks-edi-cartridge/blob/167557abba5ae9079f90df8b0fed00f204ef139d/ect/src/main/java/org/smooks/edi/ect/DirectoryParser.java) `org.smooks.edi.ect.formats.unedifact.parser.UnEdifactDirectoryParser` for step 3 if the free form text can't get parsed correctly. PRs are more than welcome.
