### ISSUE TITLE
How to configure edifact unparser programatically?

### ISSUE THREAD

**Issue by sankethpb** [smooks/smooks-edi-cartridge#186]
Currently we use xml to configure the EDIFACT unparser while converting from Java to EDIFACT.
Kindly share an example on how to configure the same via Java program while initializing Smooks.

`<?xml version="1.0"?>
<smooks-resource-list xmlns="https://www.smooks.org/xsd/smooks-2.0.xsd"
                      xmlns:edifact="https://www.smooks.org/xsd/smooks/edifact-2.0.xsd"
                      xmlns:core="https://www.smooks.org/xsd/smooks/smooks-core-1.6.xsd">
    <core:smooks filterSourceOn="/Interchange">
        <core:action>
            <core:inline>
                <core:replace/>
            </core:inline>
        </core:action>
        <core:config>
            <smooks-resource-list>
                <edifact:unparser schemaURI="/d97a/EDIFACT-Messages.dfdl.xsd" unparseOnNode="*">
                    <edifact:messageTypes>
                        <edifact:messageType>DELFOR</edifact:messageType>
                    </edifact:messageTypes>
                </edifact:unparser>
            </smooks-resource-list>
        </core:config>
    </core:smooks>
</smooks-resource-list>`

` final Smooks smooks = new Smooks("smooks-config.xml");`

How to initialize this configuration programmatically?

Thanks in advance.

**Comment by claudemamo** [comment]
A fellow Smooks user had [posted an example](https://groups.google.com/g/smooks-user/c/a2-FQWlH3Pk/m/6zlMB7p6DgAJ) of what you're asking

**Comment by sankethpb** [comment]
@claudemamo thank you for the link.
