### ISSUE TITLE
Got an incorrect edifact message when i ran smooks-examples -> java-to-edifact

### ISSUE THREAD

**Issue by funnydevelop** [smooks/smooks-edi-cartridge#204]
Hello i'm trying to generate edifact messge ,so i modified examples(java-to-edifact) project .  just added  some chinese words  in the NAD segment. The xml data was correct ..but i got an incorrect edifact message . please help me to check it .. thank you ..
such as : 
NAD+SU+CN11::91++????????-????????????????????????????????????????+????????????????????????????????????18????+??????++300384+CN'

**Comment by claudemamo** [comment]
Yeah, we never tested the cartridge with these kind of characters. Could you provide a sample EDIFACT document to test with?

**Comment by funnydevelop** [comment]
@claudemamo   
This's my test edifact message
==================
UNA:+.? 'UNB+UNOA:3+3023922202212:14+XXXXXXXXXXXXX:14+220727:0932+000002'UNH+1+DESADV:D:01B:UN:EAN007'BGM+351:::STO+7287540+9'DTM+137:20220721:102'DTM+2:20220812:102'RFF+ALO:0022121605'DTM+171:20220721:102'NAD+BY+FR11::91++Test address+Test address2+Test Address3++92100+FR'RFF+YC1:FR11'NAD+DP+GCCN33::91++天津有限公司+天津经济区东三道52号+天津++300308+CN'RFF+YC1:CN33'RFF+ACD:0001'NAD+SU+FR21::91++CSP test d?'test+3 testadd+Moussy-le-Neuf++77230+FR'RFF+YC1:FR21'CPS+1'LIN+900001'PIA+1+1000629:SA'IMD+F++:::Test description'QTY+12:1'DTM+361:20241031:102'DTM+94:20211115:102'RFF+VN:3502334021:000010'PCI+10'GIN+BX+U12362'UNT+24+1'UNZ+1+000001'
==================
also you can reference to below  recadv msg
==================
UNA:+.? '
UNB+UNOA:3+512X20101054836182:14+202599214103:14+220808:0932+000002'
UNH+1+RECADV:D:01B:UN:EAN007'
BGM+632:::STO+20220808112809950+9'
DTM+137:20220808:102'
DTM+50:20220823:102'
RFF+ALO:0017128652'
DTM+171:20220804:102'
NAD+BY+FR11::91++Phaarma France+65 Gorse+any words++92100+FR'
RFF+YC1:FR11'
NAD+DP+GCCN33::91++报文测试天津有限公司+天津空港经济区103号+天津++300305+CN'
RFF+YC1:CN33'
RFF+ACD:0001'
NAD+SU+FR21::91++CSP test d?'This is also a test section+Mossxy-le-Neuf++72230+FR'
RFF+YC1:FR21'
CPS+1'
LIN+900001++'
PIA+1+1000629:IN::92'
QTY+48:200:PCE'
DTM+36:20241031:102'
DTM+94:20211115:102'
RFF+VN:5502284066:000010'
RFF+BT:U23362'
RFF+AVQ:0002'
CNT+2:1'
UNT+24+1'
UNZ+1+000002'
============================
For difference characters of encoder ,I have got a method to deal with them , that is set execution context encoding before  generate edifact messge

**Comment by claudemamo** [comment]
The cartridge now supports these characters by setting the appropriate encoding. Previously, the encoding was hard-coded to ISO-8859-1 but now you can customise it by setting it from the Smooks execution context: executionContext.setContentEncoding("UTF-8")
