### ISSUE TITLE
Creates a wrong message

### ISSUE THREAD

**Issue by nicanor-busto** [smooks/smooks-edi-cartridge#206]
Hi,

I've a problem while generating EDIFACT messages, I'm receiving an object, I transform it to smooks binding Interchange object and then converting it again to a EDI file using smooks converter, the question here is that the fields has size limits (as shown in definition and schemas), and there are not being validated so i can put (for example) a value larger than expected, is there any way to validate them or I must do it manually?

Thanks.

**Comment by claudemamo** [comment]
Have you tried setting the [`validationMode`](https://github.com/smooks/smooks-dfdl-cartridge/blob/0afdfeeb3665c72ae41cb71debe02bd9bbb9b501/src/main/resources/META-INF/xsd/smooks/dfdl-1.0.xsd#L152) on `edifact:unparser` attribute to `Full`?
