### ISSUE TITLE
smooks-edi-cartridge 2.0.0-RC1 UTF-8 symbols

### ISSUE THREAD

**Issue by muellerch2293** [smooks/smooks-edi-cartridge#224]
Hi,
Smooks is just great! Thanks for that!
i am referring to the post in: 
https://groups.google.com/g/smooks-user/c/fkEp8TDJKxY/m/XBgDoz4uBgAJ
we are experiencing the same issue. Can you try to make the encoding parametrizable? 
Regards Christian

**Comment by muellerch2293** [comment]
to our understanding it would be best if the encoding was automatically detected using the payload UNOY UNOC etc...
what do you think about that?

**Comment by muellerch2293** [comment]
Hi, pushing this issue again...
i think that this issue is essential for all non-US users. 
it would be great if you could look into it! 
Regards Christian

**Comment by claudemamo** [comment]
Hi Christian, have you tried the solution that was posted in the thread?

>This problem is likely happening because [IBM_EDI_Format.dfdl.xsd](https://github.com/smooks/smooks-edi-cartridge/blob/6979c704e727a2ae89cf86a8cda1bd9ac2b7ff22/common-schemas/src/main/resources/EDIFACT-Common/IBM_EDI_Format.dfdl.xsd#L58) has its encoding hard-coded to iso-8859-1. An easy workaround is to modify [edi-to-xml-order-mapping.dfdl.xsd](https://github.com/smooks/smooks-examples/blob/909cf42ab722328105f0c78e4477377538694904/edi-to-xml/src/main/resources/edi-to-xml-order-mapping.dfdl.xsd#L10) so that it points to your own DFDL format which has the encoding set to utf-8. It would be create if you could [open an issue ](https://github.com/smooks/smooks-edi-cartridge/issues/new)for this. The encoding can probably be parameterised.

At first glance I'd say automatically detecting the encoding isn't trivial to correctly implement.

**Comment by claudemamo** [comment]
Can we close this one @muellerch2293?

**Comment by claudemamo** [comment]
The  encoding has been parameterised and it can be set from the Smooks execution context: `executionContext.setContentEncoding("UTF-8")`
