### ISSUE TITLE
Add INOVERT message format

### ISSUE THREAD

**Issue by deradam** [smooks/smooks-edi-cartridge#28]
Besides parsing EDIFACT, I would need to parse and convert INOVERT messages, which is a French flavour of EDIFAT.
http://www.gtff.org/pages/35/inovert_%C2%AE_messages?langue=en
Is there anything I could use for that in smooks? If not, would it be possible that I extract the EDIFACT xsds and modify them to match INOVERT and use them in my application directly?

Thanks in advance!

**Comment by claudemamo** [comment]
Good morning Adam, there are a couple of ways to go about it. 

Definitely, the simplest way is to have _edi:parser_ read the document (as opposed to the _edifact:parser_). This parser is meant for general purpose EDI parsing (see the [examples](https://github.com/smooks/smooks-examples/blob/master/edi-to-xml/smooks-config.xml)). As you suggested, you would need to extract the EDIFACT XSDs, modify them accordingly, and then set the parser's _schemaURI_ attribute to the root XSD path.

A harder solution, but could be more feasible long-term, is forking this repo to generate the XSDs 
from the INOVERT directories. If you do that, a PR would be most welcome!

**Comment by deradam** [comment]
Hi Claude, thanks for your advice. I will give the first approach a try, to get something done first. I will see, if INOVERT follows this directory approach. Cheers!

**Comment by deradam** [comment]
We haven't had any time to further analyse the INOVERT topic. Therefore I will close this issue for now.
