### ISSUE TITLE
Missing new Enumarions in simpletype E0054-MessageReleaseNumber

### ISSUE THREAD

**Issue by fkdev191289** [smooks/smooks-edi-cartridge#285]
Hi,

im getting an error when i try to validate an file from directory higher than 12B.
I think the cause is because nobody add's the new directories to the Common Edifact Service-Segment.
The Enumartions in simpletype E0054-MessageReleaseNumber higher than 12B are missing.
Could anyone have a look on it?

Kind regards
Fabian

**Comment by claudemamo** [comment]
Thanks for reporting this! I'll push a fix for the next release.
