### ISSUE TITLE
Generating composite elements loses codelist entry information

### ISSUE THREAD

**Issue by RovoMe** [smooks/smooks-edi-cartridge#91]
While parsing the respective code list, composite element and segment definition files in [`UnEdifactDefinitionReader`](https://github.com/smooks/smooks-edi-cartridge/blob/54f97e89156114e13e1acd3b3c46fe9a4234918c/ect/src/main/java/org/smooks/edi/ect/formats/unedifact/UnEdifactDefinitionReader.java#L594) the parsed code list information is unfortunately lost on composite elements.

I.e. at the referenced line `datas` contains a list of component definition containing the respective code list entries within a list of string values. However, [later on](https://github.com/smooks/smooks-edi-cartridge/blob/54f97e89156114e13e1acd3b3c46fe9a4234918c/ect/src/main/java/org/smooks/edi/ect/formats/unedifact/UnEdifactDefinitionReader.java#L407-L410) only the ID itself is copied over to the new component which therefore leads to the loss of that information.

If a simple data element uses code list entries they actually get copied over as here [the data from the `datas` object](https://github.com/smooks/smooks-edi-cartridge/blob/54f97e89156114e13e1acd3b3c46fe9a4234918c/ect/src/main/java/org/smooks/edi/ect/formats/unedifact/UnEdifactDefinitionReader.java#L600) is directly copied over while for composite elements the object with the lost information is used.

Is this working as intended?

As the code list itself only stores the code list identifier but not the actual value, i.e. `YYMMDD` or `CCYYMMDD` in case of `DTM`'s [code list](http://www.unece.org/trade/untdid/d01b/uncl/uncl2379.htm), actual values for such components can never really be validated. I guess changing `List<String>` to `Map<String, String>` would be beneficial here.

**Comment by phax** [comment]
Seems like the last link to "code list" needs an update: https://service.unece.org/trade/untdid/d01b/tred/tred2379.htm

**Comment by RovoMe** [comment]
A simple fix to avoid losing code list information on copying these over would be to add the following code `toComponent.setCodeList(fromComponent.getCodeList());` to https://github.com/ecosio/smooks-edi-cartridge/blob/master/ect/src/main/java/org/smooks/edi/ect/formats/unedifact/UnEdifactDefinitionReader.java#L426

As already mentioned in #90 `moveToNextPart(_reader);` may cause troubles as it will, in its current state, lead to skipping certain definitions
