### ISSUE TITLE
Problem with Code lists in UnEdifactSpecificationReader

### ISSUE THREAD

**Issue by phax** [smooks/smooks-edi-cartridge#94]
HI Claude,
We stumbled over another issue in `UnEdifactSpecificationReader`: the code lists for D93A until (and including) D96B are not ready, because the ZIP-filenames are different than afterwards.
In the old versions the "UNCL.ZIP" contains e.g. these files:
```
UNCL-1.96A
UNCL-2.96A
```
whereas the newer versions (D97A and onwards) use this naming scheme:
```
UNCL.D97A
```

The `UnEdifactSpecificationReader` constructor calls `readDefinitionEntries` with a lot of parameters including `new ZipDirectoryEntry("uncl.", definitionFiles)` which translates internally to `new ZipDirectoryEntry("uncl.", "uncl.", definitionFiles)` meaning the filename in the outer ZIP starts with "uncl." and the filename in the inner ZIP starts with "uncl."

And this is error, since in D96A example above, it starts with `uncl-1.` etc.

So by replacing `new ZipDirectoryEntry("uncl.", definitionFiles)` with `new ZipDirectoryEntry("uncl.", "uncl", definitionFiles)` (no dot on the filename part) or even `new ZipDirectoryEntry("uncl.", "*", definitionFiles)` if you think this is better. We haven't analyzed the contents of the files though.

hth, Philip

**Comment by RovoMe** [comment]
As mentioned and suggested by @phax changing the instantiation of the ZipDirectoryEntry slightly and adapting the logic used in the [UnEdifactSpecificationReader](https://github.com/smooks/smooks-edi-cartridge/blob/master/ect/src/main/java/org/smooks/edi/ect/formats/unedifact/UnEdifactSpecificationReader.java#L265-L283) should fix this issue.

Note that `D93A` does not contain code list files at all
